# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='book',
            field=models.BooleanField(default=False),
        ),
    ]
