# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_seat_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='book',
            new_name='booked',
        ),
    ]
